name: cherubim
version: 0.0.0
description: In-memory database based on isolate messaging.
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=1.19.0"
dependencies:
  angel_validate: ^1.0.0-beta
  uuid: ^0.5.3
dev_dependencies:
  test: ^0.12.0