name: cherubim
version: 0.0.0
description: In-memory database based on isolate messaging.
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=1.19.0"
dependencies:
  pool: ^1.0.0
  tuple: ^1.0.0
  uuid: ^0.5.3
dev_dependencies:
  angel_common: ^1.0.0
  test: ^0.12.0