name: angel_cherubim
version: 0.0.0
description: Cherubim-powered services for the Angel framework.
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=1.19.0"
dependencies:
  angel_framework: ^1.0.0
  cherubim: ^0.0.0
dev_dependencies:
  angel_common: ^1.0.0
  test: ^0.12.0
dependency_overrides:
  cherubim:
    path: ../cherubim